---
fixtures:
  repositories:
    stdlib:
      ref: "v6.6.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    archive:
      ref: "v4.6.0"
      repo: "https://github.com/voxpupuli/puppet-archive"
  symlinks:
    vision_loki: '#{source_dir}'
